default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: mix_master_development

test:
  <<: *default
  database: mix_master_test

production:
  <<: *default
  database: mix_master_production
  username: mix_master
  password: <%= ENV['MIX_MASTER_DATABASE_PASSWORD'] %>
