# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 739c0ca3071f245f2885907c8fa2ffbad0ae2d937653e051342589619a2d0504d13010c22d1803a71ad82c0d6d4c5e30179d29da3eee80ca3f461071acc68028

test:
  secret_key_base: 413210f95a0af4fd5b2c7f5f3bb53c6951154a7aaaf6845628f368e1c1090a261c7de604aa8d0c26266548eaab0fc4ee1997c75c32ba8d085692d8fcc34c9f07

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
